version: '3'

services:
#  flix:
#    image: flix
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "9090:9090"
#    depends_on:
#      - elasticsearch
#      - mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/workspace/projects/fiap/straming/mongodb:/data/db
      - ./initializeCollection.js:/docker-entrypoint-initdb.d/initializeCollection.js