spring:
  data:
    elasticsearch:
      rest:
        uris: http://elasticsearch:9200
    mongodb:
      host: localhost
      database: streaming
      port: 27017
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG

aws:
  access-key: ACCESS_KEY
  secret-key: SECRET_KEY
  s3:
    region: sa-east-1
    bucket-name: BUCKET_NAME


server:
  port: 9090